/* Drop Tables */

DROP TABLE PAY_ITEM_INFO_TB CASCADE CONSTRAINTS;
DROP TABLE SYS.CHAT CASCADE CONSTRAINTS;
DROP TABLE SYS.PAY_HIS_IF_TB CASCADE CONSTRAINTS;
DROP TABLE SYS.RE CASCADE CONSTRAINTS;
DROP TABLE SYS.REPORT CASCADE CONSTRAINTS;
DROP TABLE SYS.SEARCH CASCADE CONSTRAINTS;
DROP TABLE SYS.USER_BACKUP_LIST_TB CASCADE CONSTRAINTS;
DROP TABLE SYS.USER_MSG_TB CASCADE CONSTRAINTS;
DROP TABLE SYS.USER_SCH_TB CASCADE CONSTRAINTS;
DROP TABLE SYS.USER_TBSPC_TB CASCADE CONSTRAINTS;
DROP TABLE SYS.USERS CASCADE CONSTRAINTS;

/* Create Tables */

-- PAY_ITEM_INFO_TB
CREATE TABLE PAY_ITEM_INFO_TB
(
	-- 종량제 종류
	PAY_ITEM_INFO_TB varchar2(200) NOT NULL,
	-- 종량제 가격
	PAY_PRICE number,
	-- 사용자 아이디
	USER_ID varchar2(200 char) NOT NULL,
	PRIMARY KEY (PAY_ITEM_INFO_TB)
);


-- CHAT
CREATE TABLE SYS.CHAT
(
	-- 채팅번호 : 채팅번호
	CHAT_ID number NOT NULL,
	-- 사용자 아이디 : 유저아이디(F.K)
	USER_ID varchar2(200 char) NOT NULL,
	-- 닉네임 : 닉네임
	NICKNAME varchar2(200 char),
	-- 채팅 내용 : 채팅 내용
	CONTENTS varchar2(2000 char),
	-- 채팅 입력날짜 : 채팅 입력날짜
	-- 
	WRITE_DATE date DEFAULT sysdate ,
	CONSTRAINT CHAT_PK PRIMARY KEY (CHAT_ID)
);


-- PAY_HIS_IF_TB
CREATE TABLE SYS.PAY_HIS_IF_TB
(
	-- 결제번호
	PAY_SEQ number NOT NULL,
	-- 사용자 아이디
	USER_ID varchar2(200 char) NOT NULL,
	-- 결제날짜
	PAY_DATE date DEFAULT sysdate,
	-- 종량제 종류
	PAY_ITEM varchar2(200 char),
	-- 결제수단
	PAY_TYPE varchar2(200 char),
	-- 가격
	PAY_PRICE number,
	CONSTRAINT PAY_HIS_IF_TB_PK PRIMARY KEY (PAY_SEQ)
);


-- RE
CREATE TABLE SYS.RE
(
	-- 댓글번호 : 댓글번호
	RE_ID number NOT NULL,
	-- 키워드 번호 : 키워드 번호(F.K)
	SEARCH_ID number,
	-- 사용자 아이디 : 회원아이디(F.K)
	USER_ID varchar2(200 char),
	-- 댓글내용 : 댓글 내용
	CONTENTS varchar2(3000 char),
	-- 댓글 시간 : 댓글 입력시간
	-- 
	WRITE_DATE date DEFAULT sysdate 
,
	CONSTRAINT RE_PK PRIMARY KEY (RE_ID)
);


-- REPORT
CREATE TABLE SYS.REPORT
(
	-- 신고번호 : 신고번호
	RP_ID number NOT NULL,
	-- 신고자 : 신고자
	USER_ID varchar2(200 char),
	-- 신고대상자 : 신고대상자
	RP_USER_ID varchar2(200 char),
	-- 댓글 종류 : 0=게시글 1=댓글 2=채팅
	RP_TYPE number NOT NULL,
	-- 신고날짜 : 신고날짜
	RP_DATE date DEFAULT sysdate 
 NOT NULL,
	-- 신고사유 : 신고사유
	RP_CONTENTS varchar2(3000 char),
	-- 게시판번호 : 게시글번호
	BOARD_NUM number,
	CONSTRAINT REPORT_PK PRIMARY KEY (RP_ID)
);


-- SEARCH
CREATE TABLE SYS.SEARCH
(
	-- 키워드번호 : 키워드번호
	SEARCH_ID number NOT NULL,
	-- 사용자 아이디 : 유저아이디(F.K)
	USER_ID varchar2(200 char) NOT NULL,
	-- 키워드 제목 : 키워드 제목
	TITLE varchar2(200 char),
	-- 키워드 내용 : 키워드 내용
	CONTENTS varchar2(3000 char),
	-- 키워드 입력날짜 : 키워드 입력날짜
	WRITE_DATE date DEFAULT sysdate ,
	CONSTRAINT SEARCH_PK PRIMARY KEY (SEARCH_ID)
);


-- USERS
CREATE TABLE SYS.USERS
(
	-- 사용자 아이디
	USER_ID varchar2(200 char) NOT NULL,
	-- 비밀번호
	PASSWORD varchar2(200 char),
	-- 닉네임
	NICKNAME varchar2(200 char),
	-- 이메일
	E_MAIL varchar2(200 char),
	-- 가입일
	USER_DATE date,
	-- 회원등급 : 일반유저'1',관리자'2', 탈퇴'0'
	USER_TYPE number(2,0) DEFAULT '1'  NOT NULL,
	-- 연락처
	PHONENUMBER varchar2(20 char),
	-- 종량제 종류
	PAY_ITEM varchar2(20 char),
	-- 종량제 이용 여부 : 신청'Y', 취소'N' 
	PAY_SERVICE varchar2(2 char) DEFAULT '''N'' ' NOT NULL,
	-- 데이터 삭제 날짜 : 탈퇴 신청하고 30일 이후의 날짜. 해당 날이되면 데이터 삭제
	DEL_DATE date,
	CONSTRAINT USERS_PK PRIMARY KEY (USER_ID)
);


-- USER_BACKUP_LIST_TB
CREATE TABLE SYS.USER_BACKUP_LIST_TB
(
	-- 백업 파일 이름 : 유저ID_TBSPC이름_백업한날짜(YYYYMMDDHH:24MMSS)
	BACKUP_FILE_NM varchar2(200 char) NOT NULL,
	-- 사용자 아이디
	USER_ID varchar2(200 char) NOT NULL,
	-- 백업 날짜
	BACKUP_DATE date,
	-- 코멘트
	BACKUP_COMMENT varchar2(1000 char),
	-- 보관기간 : 보관기간
	RETENTION_PERIOD date,
	CONSTRAINT USER_BACKUP_LIST_TB_PK PRIMARY KEY (BACKUP_FILE_NM)
);


-- USER_MSG_TB
CREATE TABLE SYS.USER_MSG_TB
(
	-- 보내는 사람
	MSG_ID number NOT NULL,
	-- 문자 내용
	MSG_CONTENTS varchar2(200 char),
	-- 문자 보내기
	MSG_SEND_DATE date,
	-- 받는 사람
	RECEIVER_ID varchar2(200 char) NOT NULL,
	CONSTRAINT USER_MSG_TB_PK PRIMARY KEY (MSG_ID)
);


-- USER_SCH_TB
CREATE TABLE SYS.USER_SCH_TB
(
	-- 스키마 아이디
	USER_SCH_NM varchar2(200 char) NOT NULL,
	-- 스키마 비밀번호
	USER_SCH_PW varchar2(200 char),
	-- 사용자 아이디
	USER_ID varchar2(200 char) NOT NULL,
	CONSTRAINT USER_SCH_TB_PK PRIMARY KEY (USER_SCH_NM)
);


-- USER_TBSPC_TB
CREATE TABLE SYS.USER_TBSPC_TB
(
	-- 테이블스페이스 이름
	TABLESPACE_NAME varchar2(200 char) NOT NULL,
	-- 사용자 아이디
	USER_ID varchar2(200 char) NOT NULL,
	-- 용량 : 테이블스페이스 용량(단위 : GB)
	VOLUMN number,
	CONSTRAINT USER_TBSPC_TB_PK PRIMARY KEY (TABLESPACE_NAME)
);



/* Create Foreign Keys */

ALTER TABLE SYS.RE
	ADD CONSTRAINT RE_FK2 FOREIGN KEY (SEARCH_ID)
	REFERENCES SYS.SEARCH (SEARCH_ID)
	ON DELETE CASCADE
;


ALTER TABLE PAY_ITEM_INFO_TB
	ADD FOREIGN KEY (USER_ID)
	REFERENCES SYS.USERS (USER_ID)
;


ALTER TABLE SYS.CHAT
	ADD CONSTRAINT CHAT_USERS_FK FOREIGN KEY (USER_ID)
	REFERENCES SYS.USERS (USER_ID)
;


ALTER TABLE SYS.PAY_HIS_IF_TB
	ADD CONSTRAINT PAY_HIS_IF_TB_FK1 FOREIGN KEY (USER_ID)
	REFERENCES SYS.USERS (USER_ID)
	ON DELETE SET NULL
;


ALTER TABLE SYS.RE
	ADD CONSTRAINT RE_FK1 FOREIGN KEY (USER_ID)
	REFERENCES SYS.USERS (USER_ID)
;


ALTER TABLE SYS.REPORT
	ADD CONSTRAINT REPORT_FK1 FOREIGN KEY (USER_ID)
	REFERENCES SYS.USERS (USER_ID)
;


ALTER TABLE SYS.SEARCH
	ADD CONSTRAINT SEARCH_USERS_FK FOREIGN KEY (USER_ID)
	REFERENCES SYS.USERS (USER_ID)
;


ALTER TABLE SYS.USER_BACKUP_LIST_TB
	ADD CONSTRAINT U_BACKUP_LIST_U_FK FOREIGN KEY (USER_ID)
	REFERENCES SYS.USERS (USER_ID)
;


ALTER TABLE SYS.USER_MSG_TB
	ADD CONSTRAINT USER_MSG_TB_USERS_FK FOREIGN KEY (RECEIVER_ID)
	REFERENCES SYS.USERS (USER_ID)
;


ALTER TABLE SYS.USER_SCH_TB
	ADD CONSTRAINT USER_SCH_TB_USERS_FK FOREIGN KEY (USER_ID)
	REFERENCES SYS.USERS (USER_ID)
;


ALTER TABLE SYS.USER_TBSPC_TB
	ADD CONSTRAINT USER_TBSPC_TB_USERS_FK FOREIGN KEY (USER_ID)
	REFERENCES SYS.USERS (USER_ID)
;





/* Comments */

COMMENT ON TABLE PAY_ITEM_INFO_TB IS 'PAY_ITEM_INFO_TB';
COMMENT ON COLUMN PAY_ITEM_INFO_TB.PAY_ITEM_INFO_TB IS '종량제 종류';
COMMENT ON COLUMN PAY_ITEM_INFO_TB.PAY_PRICE IS '종량제 가격';
COMMENT ON COLUMN PAY_ITEM_INFO_TB.USER_ID IS '사용자 아이디';
COMMENT ON TABLE SYS.CHAT IS 'CHAT';
COMMENT ON COLUMN SYS.CHAT.CHAT_ID IS '채팅번호 : 채팅번호';
COMMENT ON COLUMN SYS.CHAT.USER_ID IS '사용자 아이디 : 유저아이디(F.K)';
COMMENT ON COLUMN SYS.CHAT.NICKNAME IS '닉네임 : 닉네임';
COMMENT ON COLUMN SYS.CHAT.CONTENTS IS '채팅 내용 : 채팅 내용';
COMMENT ON COLUMN SYS.CHAT.WRITE_DATE IS '채팅 입력날짜 : 채팅 입력날짜
';
COMMENT ON TABLE SYS.PAY_HIS_IF_TB IS 'PAY_HIS_IF_TB';
COMMENT ON COLUMN SYS.PAY_HIS_IF_TB.PAY_SEQ IS '결제번호';
COMMENT ON COLUMN SYS.PAY_HIS_IF_TB.USER_ID IS '사용자 아이디';
COMMENT ON COLUMN SYS.PAY_HIS_IF_TB.PAY_DATE IS '결제날짜';
COMMENT ON COLUMN SYS.PAY_HIS_IF_TB.PAY_ITEM IS '종량제 종류';
COMMENT ON COLUMN SYS.PAY_HIS_IF_TB.PAY_TYPE IS '결제수단';
COMMENT ON COLUMN SYS.PAY_HIS_IF_TB.PAY_PRICE IS '가격';
COMMENT ON TABLE SYS.RE IS 'RE';
COMMENT ON COLUMN SYS.RE.RE_ID IS '댓글번호 : 댓글번호';
COMMENT ON COLUMN SYS.RE.SEARCH_ID IS '키워드 번호 : 키워드 번호(F.K)';
COMMENT ON COLUMN SYS.RE.USER_ID IS '사용자 아이디 : 회원아이디(F.K)';
COMMENT ON COLUMN SYS.RE.CONTENTS IS '댓글내용 : 댓글 내용';
COMMENT ON COLUMN SYS.RE.WRITE_DATE IS '댓글 시간 : 댓글 입력시간
';
COMMENT ON TABLE SYS.REPORT IS 'REPORT';
COMMENT ON COLUMN SYS.REPORT.RP_ID IS '신고번호 : 신고번호';
COMMENT ON COLUMN SYS.REPORT.USER_ID IS '신고자 : 신고자';
COMMENT ON COLUMN SYS.REPORT.RP_USER_ID IS '신고대상자 : 신고대상자';
COMMENT ON COLUMN SYS.REPORT.RP_TYPE IS '댓글 종류 : 0=게시글 1=댓글 2=채팅';
COMMENT ON COLUMN SYS.REPORT.RP_DATE IS '신고날짜 : 신고날짜';
COMMENT ON COLUMN SYS.REPORT.RP_CONTENTS IS '신고사유 : 신고사유';
COMMENT ON COLUMN SYS.REPORT.BOARD_NUM IS '게시판번호 : 게시글번호';
COMMENT ON TABLE SYS.SEARCH IS 'SEARCH';
COMMENT ON COLUMN SYS.SEARCH.SEARCH_ID IS '키워드번호 : 키워드번호';
COMMENT ON COLUMN SYS.SEARCH.USER_ID IS '사용자 아이디 : 유저아이디(F.K)';
COMMENT ON COLUMN SYS.SEARCH.TITLE IS '키워드 제목 : 키워드 제목';
COMMENT ON COLUMN SYS.SEARCH.CONTENTS IS '키워드 내용 : 키워드 내용';
COMMENT ON COLUMN SYS.SEARCH.WRITE_DATE IS '키워드 입력날짜 : 키워드 입력날짜';
COMMENT ON TABLE SYS.USERS IS 'USERS';
COMMENT ON COLUMN SYS.USERS.USER_ID IS '사용자 아이디';
COMMENT ON COLUMN SYS.USERS.PASSWORD IS '비밀번호';
COMMENT ON COLUMN SYS.USERS.NICKNAME IS '닉네임';
COMMENT ON COLUMN SYS.USERS.E_MAIL IS '이메일';
COMMENT ON COLUMN SYS.USERS.USER_DATE IS '가입일';
COMMENT ON COLUMN SYS.USERS.USER_TYPE IS '회원등급 : 일반유저''1'',관리자''2'', 탈퇴''0''';
COMMENT ON COLUMN SYS.USERS.PHONENUMBER IS '연락처';
COMMENT ON COLUMN SYS.USERS.PAY_ITEM IS '종량제 종류';
COMMENT ON COLUMN SYS.USERS.PAY_SERVICE IS '종량제 이용 여부 : 신청''Y'', 취소''N'' ';
COMMENT ON COLUMN SYS.USERS.DEL_DATE IS '데이터 삭제 날짜 : 탈퇴 신청하고 30일 이후의 날짜. 해당 날이되면 데이터 삭제';
COMMENT ON TABLE SYS.USER_BACKUP_LIST_TB IS 'USER_BACKUP_LIST_TB';
COMMENT ON COLUMN SYS.USER_BACKUP_LIST_TB.BACKUP_FILE_NM IS '백업 파일 이름 : 유저ID_TBSPC이름_백업한날짜(YYYYMMDDHH:24MMSS)';
COMMENT ON COLUMN SYS.USER_BACKUP_LIST_TB.USER_ID IS '사용자 아이디';
COMMENT ON COLUMN SYS.USER_BACKUP_LIST_TB.BACKUP_DATE IS '백업 날짜';
COMMENT ON COLUMN SYS.USER_BACKUP_LIST_TB.BACKUP_COMMENT IS '코멘트';
COMMENT ON COLUMN SYS.USER_BACKUP_LIST_TB.RETENTION_PERIOD IS '보관기간 : 보관기간';
COMMENT ON TABLE SYS.USER_MSG_TB IS 'USER_MSG_TB';
COMMENT ON COLUMN SYS.USER_MSG_TB.MSG_ID IS '보내는 사람';
COMMENT ON COLUMN SYS.USER_MSG_TB.MSG_CONTENTS IS '문자 내용';
COMMENT ON COLUMN SYS.USER_MSG_TB.MSG_SEND_DATE IS '문자 보내기';
COMMENT ON COLUMN SYS.USER_MSG_TB.RECEIVER_ID IS '받는 사람';
COMMENT ON TABLE SYS.USER_SCH_TB IS 'USER_SCH_TB';
COMMENT ON COLUMN SYS.USER_SCH_TB.USER_SCH_NM IS '스키마 아이디';
COMMENT ON COLUMN SYS.USER_SCH_TB.USER_SCH_PW IS '스키마 비밀번호';
COMMENT ON COLUMN SYS.USER_SCH_TB.USER_ID IS '사용자 아이디';
COMMENT ON TABLE SYS.USER_TBSPC_TB IS 'USER_TBSPC_TB';
COMMENT ON COLUMN SYS.USER_TBSPC_TB.TABLESPACE_NAME IS '테이블스페이스 이름';
COMMENT ON COLUMN SYS.USER_TBSPC_TB.USER_ID IS '사용자 아이디';
COMMENT ON COLUMN SYS.USER_TBSPC_TB.VOLUMN IS '용량 : 테이블스페이스 용량(단위 : GB)';



